import { test } from 'node:test';
import assert from 'node:assert/strict';
import { leaf,split,close,swap,clamp,ids,setRatio,geometry,neighbor,grow,type LayoutNode } from './tree';
const sample:LayoutNode={type:'split',dir:'row',ratio:.4,a:leaf('a'),b:{type:'split',dir:'col',ratio:.62,a:leaf('b'),b:leaf('c')}};
test('empty tree gets a leaf',()=>assert.deepEqual(split(null,null,'a'),leaf('a')));
test('split focused leaf keeps both IDs',()=>assert.deepEqual(ids(split(leaf('a'),'a','b')),['a','b']));
test('split alternates direction at nested depth',()=>{const tree=split(sample,'a','d');assert.equal(tree.type,'split');if(tree.type==='split'&&tree.a.type==='split')assert.equal(tree.a.dir,'col');else assert.fail();});
test('unknown split target preserves tree',()=>assert.deepEqual(split(sample,'missing','d'),sample));
test('closing last leaf empties tree',()=>assert.equal(close(leaf('a'),'a'),null));
test('closing left branch promotes nested sibling',()=>assert.deepEqual(ids(close(sample,'a')),['b','c']));
test('closing nested branch promotes sibling in place',()=>assert.deepEqual(close(sample,'b'),{type:'split',dir:'row',ratio:.4,a:leaf('a'),b:leaf('c')}));
test('closing unknown ID preserves structure',()=>assert.deepEqual(close(sample,'x'),sample));
test('swap siblings',()=>assert.deepEqual(ids(swap(sample,'b','c')),['a','c','b']));
test('swap leaves across branches',()=>assert.deepEqual(ids(swap(sample,'a','c')),['c','b','a']));
test('ratio clamps both limits',()=>{assert.equal(clamp(-1),.2);assert.equal(clamp(9),.8);assert.equal(clamp(.5),.5);});
test('sets a nested ratio without mutating parent',()=>{const next=setRatio(sample,'b',.1);if(next.type==='split'&&next.b.type==='split'){assert.equal(next.ratio,.4);assert.equal(next.b.ratio,.2);}else assert.fail();});
test('geometry covers normalized area',()=>{const rects=geometry(sample);assert.equal(rects.reduce((sum,r)=>sum+r.w*r.h,0),1);assert.equal(rects.find(r=>r.id==='c')?.y,.62);});
test('directional lookup picks aligned neighbor',()=>{assert.equal(neighbor(sample,'b','down'),'c');assert.equal(neighbor(sample,'c','up'),'b');assert.equal(neighbor(sample,'c','left'),'a');});
test('directional lookup handles edge and missing focus',()=>{assert.equal(neighbor(sample,'a','left'),null);assert.equal(neighbor(sample,'missing','right'),null);});
test('grow focused secondary child decreases ratio',()=>{const next=grow(sample,'c',.05);if(next.type==='split'&&next.b.type==='split')assert.equal(next.b.ratio,.57);else assert.fail();});
