'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Command, Search, TerminalSquare, Folder, FileCode2, ChevronRight, ArrowUpRight, Keyboard, Palette, Hash, Info, RotateCcw, Check, FileText, type LucideIcon } from 'lucide-react';
import { useDesktop } from '@/lib/state/store';
import { apps,type AppId } from '@/lib/apps/registry';
import { oma } from '@/lib/oma/bus';
import { fs,type Entry } from '@/lib/fs/opfs';
import { keybinds } from '@/lib/keys/bindings';
import { dismissWelcome } from '@/lib/keys/useKeybind';
const icons:Record<string,LucideIcon>={term:TerminalSquare,editor:FileCode2,files:Folder,agent:ChevronRight,notice:Info};
type Row={id:string;title:string;hint?:string;group:string;icon:LucideIcon;run:()=>void};
const matches=(query:string,title:string)=>{let i=0;for(const c of title.toLowerCase()){if(c===query[i])i++;}return i===query.length;};
export default function Overlays(){const overlay=useDesktop(s=>s.overlay),panel=useRef<HTMLDivElement>(null);useEffect(()=>{if(overlay)panel.current?.focus();},[overlay]);if(!overlay)return null;
 const close=()=>useDesktop.getState().setOverlay(null);
 return <div className="scrim" onPointerDown={e=>{if(e.target===e.currentTarget){if(overlay==='welcome')void dismissWelcome();else close();}}}><div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label={overlay==='keys'?'Keyboard shortcuts':overlay==='welcome'?'Welcome to oma.os':overlay==='launcher'?'Launcher':overlay==='menu'?'System menu':overlay==='reset'?'Reset machine':overlay==='theme'?'Theme':'About oma.os'} className={'overlay '+(overlay==='keys'?'keys-panel':'')} onKeyDown={e=>{if(e.key==='Tab'){const focusable=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input,[tabindex="0"]'));const index=focusable.indexOf(document.activeElement as HTMLElement);if(focusable.length){e.preventDefault();focusable[(index+(e.shiftKey?-1:1)+focusable.length)%focusable.length].focus();}}}}>
 {overlay==='launcher'||overlay==='menu'?<Picker key={overlay} menu={overlay==='menu'}/>:overlay==='keys'?<><div className="overlay-heading"><Keyboard size={16}/><span>Keyboard shortcuts</span><kbd>esc</kbd></div><div className="keys-intro">Alt is Super. Your browser keeps its shortcuts.</div><div className="keys-grid">{keybinds.map(([key,label])=><div className="key-row" key={key}><span>{label}</span><kbd>{key}</kbd></div>)}</div><div className="overlay-footer">Alt+K opens this guide. Use Alt+↑ to focus up.</div></>:overlay==='welcome'?<div className="welcome"><div className="welcome-brand"><Command size={25}/><span>oma.os</span><small>0.1.0</small></div><p className="welcome-lead">A browser desktop with Omarchy’s habits.</p><div className="welcome-facts"><p><kbd>Alt</kbd> is Super. <kbd>Alt+Space</kbd> opens the launcher.</p><p><kbd>Alt+←↓↑→</kbd> moves focus. <kbd>Alt+1…9</kbd> switches workspaces.</p><p>Nothing leaves this browser unless you connect an agent later.</p><p>This is not Omarchy Linux. It is the desk, in a tab.</p></div><button autoFocus className="welcome-enter" onClick={()=>void dismissWelcome()}><span>Enter the desktop</span><kbd>↵</kbd></button><div className="welcome-bottom"><span>Local files. Your workspace.</span><span>Alt+K for all keys</span></div></div>:overlay==='theme'?<><div className="overlay-heading"><Palette size={16}/><span>Theme</span><kbd>esc</kbd></div><button className="theme-choice" onClick={()=>{void oma(['theme','set','tokyo-night'],{store:useDesktop,fs});close();}}><div><strong>Tokyo Night</strong><span>Quiet colors. Sharp edges.</span></div><div className="swatches">{['#7aa2f7','#7dcfff','#9ece6a','#e0af68','#f7768e','#bb9af7'].map(c=><i key={c} style={{background:c}}/>)}</div><Check size={16}/></button><div className="overlay-footer">The default, and the only theme in v1.</div></>:overlay==='reset'?<><div className="overlay-heading"><RotateCcw size={16}/><span>Reset this machine?</span><kbd>esc</kbd></div><div className="confirmation"><p>This permanently deletes all oma.os files in this browser and restores the default workspace.</p><div><button onClick={close}>Keep my machine</button><button className="danger" onClick={async()=>{const result=await oma(['reset','--yes'],{store:useDesktop,fs});if(!result.ok)useDesktop.getState().notify(result.message);}}>Delete files and reset</button></div></div></>:<><div className="overlay-heading"><Command size={16}/><span>oma.os</span><kbd>esc</kbd></div><div className="about-copy"><h2>A browser desktop with Omarchy’s habits.</h2><p>Alt is Super.<br/>This is not Linux. It is the desk.</p><p className="muted">Version 0.1.0 · MIT<br/>Not affiliated with Omarchy, Omacom, 37signals, or DHH.</p></div></>}
 </div></div>;
}
function Picker({menu}:{menu:boolean}){const [query,setQuery]=useState(''),[selected,setSelected]=useState(0),[files,setFiles]=useState<Entry[]>([]),input=useRef<HTMLInputElement>(null),rowsRef=useRef<HTMLDivElement>(null);useEffect(()=>{input.current?.focus();if(!menu)void fs.search().then(setFiles).catch(()=>{});},[menu]);
 const bus=(argv:string[])=>{useDesktop.getState().setOverlay(null);void oma(argv,{store:useDesktop,fs}).then(r=>{if(r.message)useDesktop.getState().notify(r.message);});};
 const all=useMemo<Row[]>(()=>[...Object.values(apps).filter(a=>a.id!=='notice').map(a=>({id:a.id,title:a.title,hint:a.hint,group:'Launch',icon:icons[a.id],run:()=>bus(['launch',a.id])})),...Array.from({length:9},(_,i)=>({id:'ws'+i,title:`Workspace ${i+1}`,hint:`Alt+${i+1}`,group:'Workspace',icon:Hash,run:()=>bus(['ws',String(i+1)])})),{id:'theme',title:'Tokyo Night',group:'Theme',icon:Palette,run:()=>useDesktop.getState().setOverlay('theme')},{id:'keys',title:'Keyboard shortcuts',hint:'Alt+K',group:'System',icon:Keyboard,run:()=>useDesktop.getState().setOverlay('keys')},{id:'reset',title:'Reset machine',group:'System',icon:RotateCcw,run:()=>useDesktop.getState().setOverlay('reset')},{id:'about',title:'About oma.os',group:'System',icon:Info,run:()=>useDesktop.getState().setOverlay('about')},...(!menu?[{id:'help',title:'oma help',group:'Commands',icon:TerminalSquare,run:()=>{bus(['launch','term']);useDesktop.getState().notify('Type oma help in the terminal for all commands.');}},{id:'version',title:'oma version',group:'Commands',icon:TerminalSquare,run:()=>bus(['version'])},{id:'agent-status',title:'oma agent status',group:'Commands',icon:TerminalSquare,run:()=>bus(['agent','status'])},...files.map(f=>({id:f.path,title:f.name,hint:f.path,group:'Files',icon:FileText,run:()=>{useDesktop.getState().setOverlay(null);useDesktop.getState().launch('editor',f.path);}}))]:[])],[files,menu]);
 const filtered=all.filter(row=>matches(query.toLowerCase().replace(/\s+/g,''),(row.title+' '+row.hint).replace(/\s+/g,''))),index=Math.min(selected,Math.max(0,filtered.length-1));useEffect(()=>{rowsRef.current?.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'});},[index,query]);
 return <div onKeyDown={e=>{if(e.key==='ArrowDown'||(e.ctrlKey&&e.key==='j')){e.preventDefault();setSelected((index+1)%Math.max(1,filtered.length));}if(e.key==='ArrowUp'||(e.ctrlKey&&e.key==='k')){e.preventDefault();setSelected((index-1+filtered.length)%Math.max(1,filtered.length));}if(e.key==='Enter'){e.preventDefault();filtered[index]?.run();}}}><div className="picker-search">{menu?<Command size={17}/>:<Search size={17}/>}<input ref={input} role="combobox" aria-label={menu?'Search system menu':'Search apps, commands, files'} aria-expanded="true" aria-controls="picker-results" aria-activedescendant={filtered[index]?'result-'+filtered[index].id:undefined} placeholder={menu?'System menu':'Apps, commands, files…'} value={query} onChange={e=>{setQuery(e.target.value);setSelected(0);}}/><kbd>esc</kbd></div><div className="picker-results" ref={rowsRef} id="picker-results" role="listbox">{filtered.length===0?<div className="no-results">No matches for “{query}”</div>:filtered.map((row,i)=><div key={row.id}>{(i===0||filtered[i-1].group!==row.group)&&<div className="picker-group">{row.group}</div>}<button id={'result-'+row.id} role="option" aria-selected={i===index} className={'picker-row '+(i===index?'selected':'')} onPointerMove={()=>setSelected(i)} onClick={row.run}><row.icon size={16}/><span>{row.title}</span><kbd>{row.hint}</kbd>{i===index&&<ChevronRight size={13}/>}</button></div>)}</div><div className="picker-footer"><span><kbd>↑↓</kbd> navigate <kbd>↵</kbd> open</span><span>{menu?'oma.os':'Alt is Super'}</span></div></div>;
}
