import { fs } from "./opfs";
export const SKILL =
  "# oma.os agent operating guide\n\nYou are operating a local-first browser desktop. Never invent actions or outputs.\n\n## Discover first\nThe built-in agent desktop tool accepts argv without the oma prefix:\n- capabilities: versioned command schemas, examples, permissions, errors and limits.\n- inspect: workspace, focus, normalized layout bounds, declared paths and live agent status.\n- apps: discover actual registered app IDs instead of guessing.\nIn the Agent composer, /capabilities and /inspect also work without a model.\nTerminal commands use oma help, oma apps, oma window list and oma ws N.\n\n## State and files\nWorkspaces are 1\u20139. Windows tile in a binary tree. Layout bounds are not screen pixels.\nDeclared paths are launch metadata, not live app selections or unsaved editor buffers.\nFiles persist in browser OPFS under /home/guest and /.oma. Use the filesystem tool\nfor scoped reads, create-only writes and reviewed existing-file patches. Private\nagent/auth directories are excluded. Respect a declined approval; do not retry it.\nThe legacy /.oma/config.toml default_agent setting is not live model connection\nstate. inspect reports live runtime status and configured mode without credentials.\n\n## Real capabilities\nThe read_only_shell tool runs Just Bash pipelines over scoped files with enforced\nread-only storage and no network, desktop bridge or native processes. /sh SCRIPT\nworks offline. The interactive Terminal separately supports file mutations.\nPython Lab and SQL Workbench run real runtimes through user-operated interfaces;\nno agent Python or SQL execution tool is available. Generated code is not tested\nunless an execution tool actually ran it.\nCreate self-contained responsive HTML files and run them in the OS Browser. Local\nHTML uses an opaque-origin sandbox without privileged filesystem or auth access.\nExternal websites stay inside the OS browser using the deployment's available\nviewer. A launch result is not evidence that a page loaded or was read. Browser\nDOM extraction, app adapters, event subscriptions and WebMCP are not implemented.\n\n## Safety and handoff\nUse inspect/capabilities after actionable command errors. No agent reset, deletion\nor model-controlled approval. Stop cancels the run; disable tools in Agent Settings\nto revoke tool access for future turns. Leave real saved artifacts, their paths,\nverification evidence and any unfinished work. Export important files/backups.\n";
const INTERVAL =
  "<!doctype html><html lang=\"en\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Interval</title><style>\n*{box-sizing:border-box}body{margin:0;background:#1a1b26;color:#c0caf5;font:13px system-ui,sans-serif;min-height:100vh;display:grid;place-items:center}.app{width:min(360px,85vw)}header{display:flex;align-items:center;justify-content:space-between;color:#a9b1d6;font-size:12px}header span{font:10px monospace;color:#565f89}h1{font:72px/1.2 ui-monospace,monospace;letter-spacing:-5px;font-weight:400;margin:42px 0 12px;font-variant-numeric:tabular-nums}p{color:#565f89;font-size:12px;margin:0 0 30px}button{font:12px system-ui;color:#a9b1d6;border:1px solid #3b4261;background:transparent;padding:10px 18px;cursor:pointer}button:hover{border-color:#7aa2f7;color:#7aa2f7}#toggle{color:#7aa2f7;min-width:120px}.buttons{display:flex;gap:8px}.presets{display:flex;gap:20px;margin-top:30px}.presets button{padding:0;border:0;font:11px monospace;color:#565f89}.presets button.active{color:#7aa2f7}footer{margin-top:50px;padding-top:18px;border-top:1px solid #292e42;color:#565f89;font-size:10px}</style>\n<div class=\"app\"><header>interval<span>ONE THING AT A TIME</span></header><h1 id=\"time\">25:00</h1><p id=\"status\">A little space for focused work.</p><div class=\"buttons\"><button id=\"toggle\">Start focus</button><button id=\"reset\">Reset</button></div><div class=\"presets\"><button data-min=\"25\" class=\"active\">25 min</button><button data-min=\"50\">50 min</button><button data-min=\"5\">5 min break</button></div><footer>A local app. Open its source in the editor to make it yours.</footer></div>\n<script>\nlet duration=25*60,remaining=duration,deadline=0,running=false;const time=document.querySelector('#time'),toggle=document.querySelector('#toggle'),status=document.querySelector('#status');function render(){time.textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');toggle.textContent=running?'Pause':'Start focus';status.textContent=running?'One thing. No rush.':remaining===0?'Time is yours again. Take a breath.':'A little space for focused work.';}toggle.onclick=()=>{if(remaining===0)remaining=duration;running=!running;if(running)deadline=Date.now()+remaining*1000;render();};document.querySelector('#reset').onclick=()=>{running=false;remaining=duration;render();};document.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>{running=false;duration=Number(b.dataset.min)*60;remaining=duration;document.querySelectorAll('[data-min]').forEach(x=>x.classList.toggle('active',x===b));render();});setInterval(()=>{if(!running)return;remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(!remaining)running=false;render();},200);\n</script></html>\n";
async function seedFiles() {
  for (const p of ["/home/guest/Projects", "/home/guest/Documents", "/.oma"])
    await fs.mkdir(p);
  if (!(await fs.exists("/home/guest/Projects/interval.html")))
    await fs.write("/home/guest/Projects/interval.html", INTERVAL);
  if (!(await fs.exists("/.oma/SKILL.md")))
    await fs.write("/.oma/SKILL.md", SKILL);
  if (!(await fs.exists("/.oma/config.toml")))
    await fs.write(
      "/.oma/config.toml",
      'theme = \"tokyo-night\"\ndefault_agent = \"none\"\nbar.clock = \"local\"\n',
    );
}

export async function seed() {
  if (navigator.locks) return navigator.locks.request("oma-os-seed", seedFiles);
  return seedFiles();
}
