import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { join } from 'node:path';
import { createChatGPTHandler,type ChatGPTHandler,type StoredSession,type RateLimitBucket } from '@opencoredev/loginwithchatgpt-server';
import { FileStore,RedisStore } from './store';
const dataDir=process.env.OMA_AUTH_DIR??join(process.cwd(),'.oma-auth');
export function authAvailability(){const shared=!!(process.env.UPSTASH_REDIS_REST_URL&&process.env.UPSTASH_REDIS_REST_TOKEN);return {enabled:!process.env.VERCEL||!!(shared&&process.env.LWC_SECRET),storage:shared?'redis':'local',reason:process.env.VERCEL&&!shared?'ChatGPT login on this deployment needs a shared session store. Use a provider key, or self-host for bundled login.':process.env.VERCEL&&!process.env.LWC_SECRET?'Set LWC_SECRET to enable ChatGPT login.':undefined};}
async function stableSecret(){if(process.env.LWC_SECRET)return process.env.LWC_SECRET;await mkdir(dataDir,{recursive:true,mode:0o700});const path=join(dataDir,'secret');try{return await readFile(path,'utf8');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;const secret=randomBytes(32).toString('hex');try{await writeFile(path,secret,{flag:'wx',mode:0o600});return secret;}catch(error){if((error as NodeJS.ErrnoException).code==='EEXIST')return readFile(path,'utf8');throw error;}}}
let instance:Promise<ChatGPTHandler>|undefined;
export function authHandler(){if(!authAvailability().enabled)throw new Error('ChatGPT auth is not configured on this deployment');return instance??=(async()=>{const url=process.env.UPSTASH_REDIS_REST_URL,token=process.env.UPSTASH_REDIS_REST_TOKEN;return createChatGPTHandler({secret:await stableSecret(),sessionStore:url&&token?new RedisStore<StoredSession>(url,token,'oma:session:'):new FileStore<StoredSession>(join(dataDir,'sessions')),sessionTtlMs:7*24*60*60*1000,responsesProxy:{maxRequestBytes:512*1024,rateLimit:{limit:20,windowMs:60000,store:url&&token?new RedisStore<RateLimitBucket>(url,token,'oma:rate:'):new FileStore<RateLimitBucket>(join(dataDir,'rates'))}}});})();}
