'use client';
import { useEffect, useState } from 'react';
import { Folder, FileText, ChevronRight, ChevronUp, Home, HardDrive, FilePlus2, FolderPlus, ArrowUp } from 'lucide-react';
import { fs,errorMessage,type Entry } from '@/lib/fs/opfs';
import { useDesktop } from '@/lib/state/store';
export default function Files(){const [path,setPath]=useState('/home/guest'),[entries,setEntries]=useState<Entry[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[creating,setCreating]=useState<'file'|'directory'|null>(null),[name,setName]=useState('');const version=useDesktop(s=>s.fsVersion);
 useEffect(()=>{let alive=true;fs.ls(path).then(rows=>{if(alive){setEntries(rows);setError('');setSelected('');}}).catch(e=>{if(alive)setError(errorMessage(e));});return()=>{alive=false;};},[path,version]);
 const open=(entry:Entry)=>{if(entry.kind==='directory')setPath(entry.path);else useDesktop.getState().launch('editor',entry.path);};
 const up=()=>setPath(path.split('/').slice(0,-1).join('/')||'/');
 const create=async()=>{if(!name.trim()||name.includes('/'))return;try{const p=(path==='/'?'':path)+'/'+name.trim();if(creating==='directory')await fs.mkdir(p);else {if(await fs.exists(p))throw new Error('File already exists');await fs.touch(p);}setCreating(null);setName('');useDesktop.getState().refreshFs();}catch(e){setError(errorMessage(e));}};
 return <div className="files-app"><nav className="file-tree" aria-label="Places"><div className="section-label">PLACES</div>{[{p:'/home/guest',title:'guest',icon:Home},{p:'/home/guest/Projects',title:'Projects',icon:Folder},{p:'/home/guest/Documents',title:'Documents',icon:Folder},{p:'/.oma',title:'.oma',icon:Folder},{p:'/',title:'Filesystem',icon:HardDrive}].map(({p,title,icon:Icon})=><button key={p} className={path===p?'tree-row selected':'tree-row'} onClick={()=>setPath(p)}><Icon size={15}/>{title}{path===p&&<ChevronRight size={12}/>}</button>)}<div className="tree-note">LOCAL STORAGE<br/><span>Origin Private File System</span></div></nav><div className="file-list"><div className="file-location"><button title="Parent directory" onClick={up} disabled={path==='/'}><ArrowUp size={14}/></button><span>{path}</span><div className="file-actions"><button title="New file" aria-label="New file" onClick={()=>{setCreating('file');setName('');}}><FilePlus2 size={14}/></button><button title="New folder" aria-label="New folder" onClick={()=>{setCreating('directory');setName('');}}><FolderPlus size={14}/></button></div></div><div className="file-columns"><span>Name <ChevronUp size={10}/></span><span>Size</span></div><div className="file-rows" role="listbox" aria-label="Files" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'){const item=entries.find(r=>r.path===selected);if(item)open(item);}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const index=entries.findIndex(r=>r.path===selected),next=Math.max(0,Math.min(entries.length-1,index+(e.key==='ArrowDown'?1:-1)));if(entries[next])setSelected(entries[next].path);}if(e.key==='Backspace')up();}}>{error&&<div className="file-error">{error}</div>}{creating&&<form className="new-file" onSubmit={e=>{e.preventDefault();void create();}}><input autoFocus placeholder={creating==='file'?'filename.txt':'folder name'} aria-label="New name" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setCreating(null);}}/><button type="submit">Create</button></form>}{entries.map(entry=><div key={entry.path} role="option" aria-selected={selected===entry.path} className={'file-row '+(selected===entry.path?'selected':'')} onClick={()=>setSelected(entry.path)} onDoubleClick={()=>open(entry)}>{entry.kind==='directory'?<Folder size={15} className="folder-icon"/>:<FileText size={15}/>}<span>{entry.name}</span><span className="file-size">{entry.kind==='directory'?'—':entry.size!<1024?entry.size+' B':(entry.size!/1024).toFixed(1)+' KB'}</span></div>)}{!entries.length&&!error&&!creating&&<div className="folder-empty">This folder is empty.<br/><span>Create a file or folder to get started.</span></div>}</div><div className="client-footer"><span>{entries.length} items</span><span>Double-click to open</span></div></div></div>;
}
