'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckSquare, Download, FileCode2, Flag, Pause, Play, Plus, RotateCcw, Search, Timer, Trash2, X } from 'lucide-react';
import { useDocument } from '@/lib/apps/creative/useDocument';
import { boardMarkdown, emptyBoard, localDay, moveTask, parseBoard, taskColumns, taskMatches, type Task, type TaskPriority, type TaskStatus } from '@/lib/apps/tasks';
import { useDesktop } from '@/lib/state/store';
import './tasks.css';

const DEFAULT_PATH = '/home/guest/Documents/My work.oma-tasks.json';
function download(text: string, name: string, type = 'text/markdown') {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const link = document.createElement('a'); link.href = url; link.download = name; link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function TagsInput({ tags, commit }: { tags: string[]; commit: (tags: string[]) => void }) {
  const joined = tags.join(', '), [draft, setDraft] = useState(joined);
  useEffect(() => setDraft(joined), [joined]);
  return <input aria-label="Task tags" value={draft} onChange={event => setDraft(event.target.value)} onBlur={() => commit([...new Set(draft.split(',').map(tag => tag.trim()).filter(Boolean))].slice(0,20))} onKeyDown={event => { if (event.key==='Enter') event.currentTarget.blur(); }}/>
}
export default function Tasks({ id, path = DEFAULT_PATH }: { id: string; path?: string; active?: boolean }) {
  const doc = useDocument(id, path, emptyBoard, parseBoard);
  const [query, setQuery] = useState(''), [newTitle, setNewTitle] = useState(''), [selected, setSelected] = useState<string | null>(null), [onlyDue, setOnlyDue] = useState(false);
  const [removed, setRemoved] = useState<Task | null>(null), [dragOver, setDragOver] = useState<TaskStatus | null>(null);
  const [focusTask, setFocusTask] = useState<string | null>(null), [duration, setDuration] = useState(25 * 60), [remaining, setRemaining] = useState(25 * 60), [deadline, setDeadline] = useState<number | null>(null);
  const titleInput = useRef<HTMLInputElement>(null);
  const focused = doc.value.tasks.find(task => task.id === focusTask), detail = doc.value.tasks.find(task => task.id === selected);
  const today = localDay(), completed = doc.value.tasks.filter(task => task.status === 'done').length;
  useEffect(() => { if (!deadline) return; const tick = () => { const left = Math.max(0, Math.ceil((deadline - Date.now()) / 1000)); setRemaining(left); if (!left) { setDeadline(null); useDesktop.getState().notify('Focus session complete. Take a moment to reset.'); } }; tick(); const interval = setInterval(tick, 250); return () => clearInterval(interval); }, [deadline]);
  const visible = useMemo(() => doc.value.tasks.filter(task => taskMatches(task, query) && (!onlyDue || (task.status !== 'done' && task.due && task.due <= today))), [doc.value.tasks, query, onlyDue, today]);
  const updateTask = (taskId: string, patch: Partial<Task>) => doc.update(board => ({ ...board, tasks: board.tasks.map(task => task.id === taskId ? { ...task, ...patch, updatedAt: Date.now() } : task) }));
  const add = () => { const title = newTitle.trim(); if (!title || !doc.ready) return; const now = Date.now(); const task: Task = { id: crypto.randomUUID(), title, notes: '', status: 'todo', priority: 'normal', due: '', tags: [], createdAt: now, updatedAt: now }; doc.update(board => ({ ...board, tasks: [...board.tasks, task] })); setNewTitle(''); titleInput.current?.focus(); };
  const move = (taskId: string, status: TaskStatus) => doc.update(board => moveTask(board, taskId, status));
  const remove = (task: Task) => { setRemoved(task); doc.update(board => ({ ...board, tasks: board.tasks.filter(item => item.id !== task.id) })); setSelected(null); };
  const focus = (task: Task) => { setFocusTask(task.id); setRemaining(duration); setDeadline(Date.now() + duration * 1000); if (task.status === 'todo') move(task.id, 'doing'); };
  return <div className="tasks-app" onKeyDown={event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 's') { event.preventDefault(); void doc.flush(); } }}>
    <header className="tasks-toolbar"><CheckSquare size={16}/><input aria-label="Board title" value={doc.value.title} disabled={!doc.ready} onChange={event => doc.update(board => ({ ...board, title: event.target.value }))}/><span>{completed}/{doc.value.tasks.length}</span><button aria-label="Export board as Markdown" title="Export Markdown" onClick={() => download(boardMarkdown(doc.value), `${doc.value.title || 'tasks'}.md`)}><Download size={15}/></button><button aria-label="Edit board source" title="Open JSON in Editor" onClick={async () => { await doc.flush(); if (!useDesktop.getState().dirty[id]) useDesktop.getState().launch('editor', path); }}><FileCode2 size={15}/></button></header>
    <div className="tasks-controls"><form onSubmit={event => { event.preventDefault(); add(); }}><Plus size={15}/><input ref={titleInput} disabled={!doc.ready} aria-label="New task" placeholder="What would you like to get done?" value={newTitle} maxLength={500} onChange={event => setNewTitle(event.target.value)}/><button disabled={!newTitle.trim() || !doc.ready}>Add</button></form><div className="tasks-search"><Search size={14}/><input aria-label="Search tasks" placeholder="Filter tasks or tags" value={query} onChange={event => setQuery(event.target.value)}/></div><button className={onlyDue ? 'active' : ''} onClick={() => setOnlyDue(value => !value)} aria-pressed={onlyDue}>Due today</button></div>
    {doc.error && <div className="tasks-error" role="alert">{doc.error}<button onClick={() => { if (confirm('Reload the saved board and discard unsaved changes?')) void doc.reload(); }}>Reload saved board</button></div>}
    {removed && <div className="tasks-undo">Removed “{removed.title}”<button onClick={() => { doc.update(board => ({ ...board, tasks: [...board.tasks, removed] })); setRemoved(null); }}>Undo</button><button aria-label="Dismiss undo" onClick={() => setRemoved(null)}><X size={13}/></button></div>}
    <div className="tasks-workarea"><div className="tasks-board">{taskColumns.map(column => { const tasks = visible.filter(task => task.status === column.id); return <section key={column.id} className={'tasks-column ' + (dragOver === column.id ? 'drop-target' : '')} aria-label={column.title} onDragOver={event => { event.preventDefault(); setDragOver(column.id); }} onDragLeave={event => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setDragOver(null); }} onDrop={event => { event.preventDefault(); const taskId = event.dataTransfer.getData('application/x-oma-task'); if (doc.value.tasks.some(task => task.id === taskId)) move(taskId, column.id); setDragOver(null); }}><header><span className={'task-column-dot ' + column.id}/><h2>{column.title}</h2><span>{tasks.length}</span></header><div className="task-stack">{tasks.length ? tasks.map(task => <article key={task.id} className={'task-card ' + (selected === task.id ? 'selected' : '')} draggable onDragStart={event => { event.dataTransfer.setData('application/x-oma-task', task.id); event.dataTransfer.effectAllowed = 'move'; }} onDragEnd={() => setDragOver(null)}><button className="task-card-main" onClick={() => setSelected(task.id)}><span className="task-card-title">{task.title}</span>{task.notes && <span className="task-card-excerpt">{task.notes}</span>}<span className="task-card-meta">{task.priority === 'high' && <span className="task-priority"><Flag size={11}/>High</span>}{task.due && <time className={task.status !== 'done' && task.due < today ? 'overdue' : ''} dateTime={task.due}>{task.due.slice(5)}</time>}{task.tags.slice(0,3).map(tag => <span key={tag}>#{tag}</span>)}</span></button><div className="task-card-actions">{column.id !== 'todo' && <button title="Move backward" aria-label={`Move ${task.title} to ${column.id === 'done' ? 'in progress' : 'to do'}`} onClick={() => move(task.id, column.id === 'done' ? 'doing' : 'todo')}><ArrowLeft size={13}/></button>}{column.id !== 'done' && <><button title="Focus on this task" aria-label={`Focus on ${task.title}`} onClick={() => focus(task)}><Timer size={13}/><span>Focus</span></button><button title={column.id === 'todo' ? 'Start task' : 'Complete task'} aria-label={`${column.id === 'todo' ? 'Start' : 'Complete'} ${task.title}`} onClick={() => move(task.id, column.id === 'todo' ? 'doing' : 'done')}>{column.id === 'todo' ? <ArrowRight size={13}/> : <Check size={13}/>}</button></>}</div></article>) : <div className="tasks-empty"><span>{query || onlyDue ? 'No matching tasks.' : column.description}</span>{column.id === 'todo' && !query && !onlyDue && <button onClick={() => titleInput.current?.focus()}>Add your first task <Plus size={12}/></button>}</div>}</div></section>; })}</div>
    {detail && <aside className="task-detail" aria-label="Task details"><header><span>Task details</span><button aria-label="Close task details" onClick={() => setSelected(null)}><X size={16}/></button></header><label>Title<input aria-label="Task title" value={detail.title} maxLength={500} onChange={event => updateTask(detail.id, { title: event.target.value })}/></label><label>Notes<textarea aria-label="Task notes" rows={7} value={detail.notes} maxLength={20000} placeholder="Links, next steps, context…" onChange={event => updateTask(detail.id, { notes: event.target.value })}/></label><div className="task-detail-grid"><label>Status<select aria-label="Task status" value={detail.status} onChange={event => move(detail.id, event.target.value as TaskStatus)}>{taskColumns.map(column => <option key={column.id} value={column.id}>{column.title}</option>)}</select></label><label>Priority<select aria-label="Task priority" value={detail.priority} onChange={event => updateTask(detail.id, { priority: event.target.value as TaskPriority })}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label></div><label>Due date<input aria-label="Task due date" type="date" value={detail.due} onChange={event => updateTask(detail.id, { due: event.target.value })}/></label><label>Tags · comma separated<TagsInput key={detail.id} tags={detail.tags} commit={tags => updateTask(detail.id, { tags })}/></label><footer><button onClick={() => focus(detail)}><Timer size={14}/>Focus on this</button><button aria-label="Delete task" onClick={() => remove(detail)}><Trash2 size={14}/></button></footer></aside>}</div>
    <div className={'tasks-focus ' + (deadline ? 'running' : '')}><Timer size={15}/><span className="focus-task-name">{focused?.title || 'Focus timer'}</span><select aria-label="Focus duration" value={duration} disabled={!!deadline} onChange={event => { const next = Number(event.target.value); setDuration(next); setRemaining(next); }}><option value={1500}>25 min</option><option value={3000}>50 min</option><option value={300}>5 min</option></select><time>{String(Math.floor(remaining/60)).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}</time><button aria-label={deadline ? 'Pause focus timer' : 'Start focus timer'} onClick={() => setDeadline(deadline ? null : Date.now() + (remaining || duration) * 1000)}>{deadline ? <Pause size={14}/> : <Play size={14}/>}</button><button aria-label="Reset focus timer" onClick={() => { setDeadline(null); setRemaining(duration); }}><RotateCcw size={14}/></button></div>
    <footer className="tasks-footer"><span>{doc.status}</span><span title={path}>{path.split('/').pop()}</span></footer>
  </div>;
}
